//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kelompok_9_project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string Name { get; set; }
        public string NIS { get; set; }
        public string Address { get; set; }
        public string TelephoneNum { get; set; }
        public string Gender { get; set; }
        public string ParentName { get; set; }
        public string ParentTelNum { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
